### ISSUE TITLE
AI and new command

### ISSUE THREAD

**Issue by PegasusThree** [AlbertoRota/x4-Better-piracy#2]
Hello,
I really enjoy your mod a lot and think that the new features that you have added in 0.3 are great! :)
I just have a few questions and suggestions.

1:  Would it be possible to let my AI ships use the new feature as well? I play with VRO, and with the new ship balance you can't just approach some ships without wingmen anymore, and it always was a huge hassle when I tried to stop my wingmen from destroying the ships I wanted to take over. It made me swear much more often than I am comfortable with.
That's why I am so thankful for the new harass-command!
But it would be even better when I can order my AI ships to harass enemy ships on their own as well, so when I want to take over a wing of 4 ships, I can focus on one ship while my wingmen won't destroy the others in the meantime, but try to get them to bail too instead!
Maybe it would help if the harass-command would not only be available as some kind of quest, but also as a new kind of attack-command for your other ships?
If that would be possible, you'd be my new hero!! It would make piracy perfect and I could finally use wingmen or even AI-only wings more often!

2.: I read that with 0.3 you deactivated random bailing?
I must say that I agree with the comments on Steam here that random bailing still gives a nice extra touch to the game, and I would rather see it not being deactivated too. In vanilla, pilots sometimes even bail in battles between AI-factions or when fighting your AI ships, and it is a nice surprise to randomly find damaged ships where you weren't involved in the battle.
Also when pilots can tell for sure that their ship is going to explode, why would they just sit and wait for their inevitable death to come? Just like in real life, people should always try to leave their vessel when they know that it is lost, hoping that the enemy will move on now that they aren't a threat anymore. In this regard, random bailing is even important for immersion.
That being said, can you please make it an optional setting in these fancy new mod options you are going to add?
For extra awesomeness maybe add configurable random bailing chances, separated for:
-player vs. AI
-player-AI vs. AI
-AI vs. AI
That would be the icing on this imaginary mod-cake that it already is!

3.: There was another thing, but now I wrote so much for 1 and 2 that I forgot what it was....

Anyway, thank you so much for this great mod!!
PG

**Comment by AlbertoRota** [comment]
Hello!
Let me go point by point:

> 1: Would it be possible to let my AI ships use the new feature as well?

Yes, in fact, that's my main goal.

I never felt "Piracy" as a valid career path, it was just not scalable and very very random based.
* If you want to be a trader, you can have a trading fleet that will consistently trade.
* If you want to be a miner, you can have a mining fleet that will consistently mine.
* If you want to be a builder, you can have a self-sufficient complex that will consistently collaborate with the economy.
* If you want to be a fighter, you can have a combat fleet that will clean entire sectors.
* If you want to be a ruler, you can claim your own sectors and start your very own empire.

But for some reason, if you want to be a "Pirate King", you need to go ALONE (Because AI will screw it up killing targets) on an endless "Pew-Pew" cycle all around the universe, praying to the RNG generator to be kind, and with people saying "Oh!, don't worry, he/she is just a pirate... who cares?"

It just felt wrong :(

My goal is to be able to be a "Pirate King"/"Crime syndicate leader", and much like the "Fighter" path, it should be as follows:
* You start alone (Like in any beginning) in your initial ship.
* You "Acquire" a better ship, a small fighter or interceptor, sell the old one and buy marines and better equipment with the benefits.
* You repeat the process several times until you end on your favorite "Heavy fighter" and a bunch of money.
* You expand your own wing with some of your "Acquisitions" and put your eyes on an M sized ship.
* Your followers begin to learn the flow (2 or 3 piloting starts) and are able to perform "Harassment operations" over S/M ships at your command.
* You repeat the process several times until you have a considerable amount of M sized ships and marines, you then put your eyes on an L/XL sized ship.
* You begin to "Acquire" several big ships, your followers begin to learn the flow (3 or 4 piloting starts) and are able to perform "Harassment operations" over L/XL ships at your command.
* You are now a "Pirate King"/"Crime syndicate leader", and your most skilled followers (4 or 5 piloting stars) are able to command a pirate gang to "Patrol" a sector in search of targets to "Acquire"

It will take time, that's for sure, but that's the goal.

> I read that with 0.3 you deactivated random bailing?

I didn't, but for some reason, people panicked about it, I will add related config options in the next update.

As I stated in Steam:

Regarding the "Harass" function, IMHO piracy is not something that should just "happen" randomly, you don't go walking through the street and suddenly you have hijacked a police car.

It should be something you plan and you commit to, it should be an informed decision, "I'm going to hijack that ship because I really want to", for me, people bailing out in the middle of a cross-fire is what made no sense at all, "They want to kill me, so I'm going to put myself in a brittle, unarmed, poorly maneuverable escape pod and pray".

With the "Harass" command you are explicitly telling them "This is just business, nothing personal, I'm a pirate and I'm going to take your ship, be smart, make it easy, bail now and you will be with your family to dinner."
That is what should make people think about bailing, "Their target is not to kill me, I want to live, the escape pod will bring me home, better to lose a ship than the life".

The same happens with vanilla "Board", you just don't happen to randomly board things, you need to prepare and commit.

**Comment by PegasusThree** [comment]
Thanks for answering my questions!!
About your Pirate-King visions:

Yes, yes, YES to everything you said!! This sounds like a dream come true, I agree on every single word!!
Finally no more sad loneliness in space anymore when you want to be a pirate!
Also making AI harassment operations dependent on stars is a very good idea, it is always good to have extra benefits for your hard earned star pilots and it helps to identify with and care about your crew!

Now I also remembered what I forgot to ask yesterday, but I think I already know the answer now:
Will it be possible for you to manually order your AI-ships to claim an abandoned ship, instead of having to rely on this very wonky "We found an abandonend ship"-message that they will only send once, and if you were busy with trying not to die or managing your ships on the map you will never have another chance to tell them to claim the ship for you?

Really, I'm so happy about your plans for this mod, that's what I always wanted!!

>I didn't, but for some reason, people panicked about it, I will add related config options in the next update

Yeah, I just got a message from one of my OOS destroyers that they have "found" an abandoned ship, and it was a damaged enemy fighter that tried to attack them. So AI-bailing (even OOS) still works!
Anyway I think that there are very different chances for bailing, depending on if it is the player, the player-AI or AI-factions involved in combat. And for immersions-sake one thing that I want to have as much as possible is consistency. I don't want to have different rules to apply to me than to the AI.
Therefore if it isn't too much trouble (and I hope it is only a single value that has to be changed), can these config options please cover these different bailing chances, too?

When there will be a new claim-command for your AI-ships to claim abandoned ships, maybe AI-factions could utilize that too? So that when they find abandoned ships in their sectors and there is no enemy nearby, they will try to send a marine to claim it?
Or are they already doing this?! I know that they did it with CODEA in X3, but in X4..  I never leave abandoned ships for a longer time to see what the other factions will do, but if they would be able to claim them as well, that would have two benefits:

- you don't have to worry about "too many" bailed ships anymore when someone decides to use the same bailing chances for AI-only battles as for battles where the player is involved
- it would add some nice flavor of competition, encouraging the player not to wait for too long. And these small ships like the Callisto that are nice but no one ever uses them because they are so useless, they finally can serve a purpose by being your fast troop transports when you have to be faster than the AI with claiming all these nice ships after big battles!

Even if you aren't a fan of random bailing, please consider that not everyone would just sit in their spacecraft waiting to be burned alive in a big explosion after a battle they cannot win. Well at least I wouldn't. ;)

Thanks again for your hard work!! You really help to improve this game so much!

**Comment by PegasusThree** [comment]
This mod is getting better with every update and you really deliver all the things you promised, thank you so much for all your efforts, it's really appreciated!
I will try the new features of today's release asap!

**Comment by AlbertoRota** [comment]
Given that all the features requested in the opening post are implemented now, I'm going to close this issue.

Feel free to propose more ideas either here, in the SteamWorkshop page, or in the Egosoft forum thread.
